import { useState } from "react";
import { createUserWithEmailAndPassword, sendPasswordResetEmail, signInWithEmailAndPassword } from "firebase/auth";
import { doc, getDoc, serverTimestamp, setDoc } from "firebase/firestore";
import { Link, useNavigate } from "react-router-dom";
import { auth, db } from "../firebase/config";
import { useAuth } from "../context/AuthContext";
function Shell({children,title,subtitle}){return <div className="min-h-[calc(100vh-72px)] bg-[#f1e9df] grid place-items-center px-4 py-12"><div className="w-full max-w-md rounded-3xl border border-stone-200 bg-white p-7 card-shadow"><Link to="/" className="mb-8 block text-center text-xl font-black">TUBE <span className="text-[#a76536]">COFFEE</span></Link><h1 className="text-3xl font-black">{title}</h1><p className="mt-2 text-sm text-stone-500">{subtitle}</p>{children}</div></div>}
function ErrorBox({error}){return error?<div className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>:null}
export function Login(){const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);const {profile}=useAuth();const navigate=useNavigate();const submit=async e=>{e.preventDefault();setBusy(true);setError("");try{const cred=await signInWithEmailAndPassword(auth,email,password);const snap=await getDoc(doc(db,"users",cred.user.uid));const role=snap.exists()?snap.data().role:"Customer";navigate(role==="Admin"?"/admin":"/dashboard")}catch(err){setError(err.message.replace("Firebase: ","").replace(/\(auth\/.*\)\.?/,""))}finally{setBusy(false)}};return <Shell title="Welcome back" subtitle="Sign in to order coffee and manage your account."><form onSubmit={submit} className="mt-6 grid gap-4"><ErrorBox error={error}/><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="rounded-xl border px-4 py-3" placeholder="Email"/><input required type="password" value={password} onChange={e=>setPassword(e.target.value)} className="rounded-xl border px-4 py-3" placeholder="Password"/><div className="text-right"><Link to="/forgot-password" className="text-sm font-semibold text-[#8a5d32]">Forgot password?</Link></div><button disabled={busy} className="rounded-xl bg-[#f4b400] px-4 py-3 font-black disabled:opacity-50">{busy?"Signing in...":"Sign in"}</button><p className="text-center text-sm text-stone-500">New to TUBE? <Link to="/register" className="font-bold text-[#8a5d32]">Create an account</Link></p></form></Shell>}
export function Register(){const [name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);const navigate=useNavigate();const submit=async e=>{e.preventDefault();setBusy(true);try{const cred=await createUserWithEmailAndPassword(auth,email,password);await setDoc(doc(db,"users",cred.user.uid),{name,email,role:"Customer",createdAt:serverTimestamp()});navigate("/dashboard")}catch(err){setError(err.message.replace("Firebase: ",""))}finally{setBusy(false)}};return <Shell title="Create your account" subtitle="Join TUBE Coffee and order your favorites online."><form onSubmit={submit} className="mt-6 grid gap-4"><ErrorBox error={error}/><input required value={name} onChange={e=>setName(e.target.value)} className="rounded-xl border px-4 py-3" placeholder="Full name"/><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="rounded-xl border px-4 py-3" placeholder="Email"/><input required minLength="6" type="password" value={password} onChange={e=>setPassword(e.target.value)} className="rounded-xl border px-4 py-3" placeholder="Password (6+ characters)"/><button disabled={busy} className="rounded-xl bg-[#f4b400] px-4 py-3 font-black">{busy?"Creating...":"Create account"}</button><p className="text-center text-sm text-stone-500">Already have an account? <Link to="/login" className="font-bold text-[#8a5d32]">Sign in</Link></p></form></Shell>}
export function ForgotPassword(){const [email,setEmail]=useState(""),[sent,setSent]=useState(false),[error,setError]=useState("");const submit=async e=>{e.preventDefault();try{await sendPasswordResetEmail(auth,email);setSent(true)}catch(err){setError(err.message.replace("Firebase: ",""))}};return <Shell title="Reset password" subtitle="We’ll email you a secure password reset link.">{sent?<div className="mt-6 rounded-2xl bg-emerald-50 p-5 text-emerald-800">Check your inbox for the reset link.</div>:<form onSubmit={submit} className="mt-6 grid gap-4"><ErrorBox error={error}/><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="rounded-xl border px-4 py-3" placeholder="Email"/><button className="rounded-xl bg-[#f4b400] px-4 py-3 font-black">Send reset link</button><Link to="/login" className="text-center text-sm font-bold text-[#8a5d32]">Back to login</Link></form>}</Shell>}
