import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { addDoc, collection, serverTimestamp } from "firebase/firestore";
import { db } from "../firebase/config";
import { useCart } from "../context/CartContext";
import { useAuth } from "../context/AuthContext";
import { money } from "../lib/format";
export default function Checkout(){const {items,total,clearCart}=useCart();const {user,profile}=useAuth();const navigate=useNavigate();const [form,setForm]=useState({customerName:profile?.name||"",phone:"",address:"",notes:"",paymentMethod:"Cash on Delivery"});const [busy,setBusy]=useState(false);const [error,setError]=useState("");if(!items.length)return <main className="container-page py-16 text-center"><h1 className="text-3xl font-black">Your cart is empty.</h1></main>;const change=e=>setForm({...form,[e.target.name]:e.target.value});const submit=async e=>{e.preventDefault();setBusy(true);setError("");try{await addDoc(collection(db,"orders"),{userId:user.uid,...form,items,totalAmount:total,status:"Pending",createdAt:serverTimestamp()});clearCart();navigate("/orders?success=1")}catch(err){setError(err.message)}finally{setBusy(false)}};return <main className="container-page py-14"><div className="mb-8"><p className="font-bold uppercase tracking-widest text-[#a76536]">CHECKOUT</p><h1 className="mt-2 text-4xl font-black">Complete your order</h1></div><form onSubmit={submit} className="grid gap-8 lg:grid-cols-[1fr_360px]"><div className="rounded-3xl bg-white p-7 card-shadow"><h2 className="text-xl font-black">Delivery details</h2>{error&&<div className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="mt-6 grid gap-4 sm:grid-cols-2"><input required name="customerName" value={form.customerName} onChange={change} className="rounded-xl border px-4 py-3" placeholder="Customer name"/><input required name="phone" value={form.phone} onChange={change} className="rounded-xl border px-4 py-3" placeholder="Phone number"/><textarea required name="address" value={form.address} onChange={change} className="sm:col-span-2 rounded-xl border px-4 py-3" rows="3" placeholder="Delivery address"/><textarea name="notes" value={form.notes} onChange={change} className="sm:col-span-2 rounded-xl border px-4 py-3" rows="3" placeholder="Order notes (optional)"/><select name="paymentMethod" value={form.paymentMethod} onChange={change} className="rounded-xl border px-4 py-3"><option>Cash on Delivery</option><option>Bank Transfer</option><option>Pay at Counter</option></select></div></div><div className="h-fit rounded-3xl bg-[#2b2118] p-7 text-white"><h2 className="text-xl font-black">Order total</h2><div className="mt-5 grid gap-3">{items.map(i=><div key={i.productId} className="flex justify-between gap-3 text-sm"><span>{i.name} × {i.quantity}</span><span>{money(i.price*i.quantity)}</span></div>)}</div><div className="mt-6 flex justify-between border-t border-white/10 pt-5 text-xl"><span className="font-black">Total</span><span className="font-black text-[#f4b400]">{money(total)}</span></div><button disabled={busy} className="mt-6 w-full rounded-xl bg-[#f4b400] px-5 py-3 font-black text-[#2b2118]">{busy?"Placing order...":"Confirm order"}</button></div></form></main>}

