import { useEffect, useMemo, useState } from "react";
import { Search, SlidersHorizontal } from "lucide-react";
import ProductCard from "../components/ProductCard";
import { listAll } from "../lib/firestore";
export default function Menu(){
 const [products,setProducts]=useState([]),[cats,setCats]=useState([]),[category,setCategory]=useState("All"),[search,setSearch]=useState("");
 useEffect(()=>{Promise.all([listAll("products"),listAll("categories")]).then(([p,c])=>{setProducts(p);setCats(c)}).catch(()=>{})},[]);
 const filtered=useMemo(()=>products.filter(p=>p.available!==false&&(category==="All"||p.category===category)&&p.name.toLowerCase().includes(search.toLowerCase())),[products,category,search]);
 return <><div className="bg-[#2b2118] py-20 text-white"><div className="container-page"><p className="font-bold uppercase tracking-[.2em] text-[#f4b400]">MENU</p><h1 className="mt-3 text-5xl font-black">Find your next favorite.</h1><p className="mt-4 max-w-xl text-stone-300">Coffee, tea, smoothies, and snacks made for every stop.</p></div></div><main className="container-page py-12"><div className="mb-8 flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-2"><button onClick={()=>setCategory("All")} className={`rounded-full px-4 py-2 text-sm font-bold ${category==="All"?"bg-[#2b2118] text-white":"bg-white border border-stone-200"}`}>All</button>{cats.map(c=><button key={c.id} onClick={()=>setCategory(c.name)} className={`rounded-full px-4 py-2 text-sm font-bold ${category===c.name?"bg-[#2b2118] text-white":"bg-white border border-stone-200"}`}>{c.name}</button>)}</div><div className="relative w-full lg:w-80"><Search className="absolute left-3 top-3.5 text-stone-400" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} className="w-full rounded-full border border-stone-200 bg-white py-3 pl-10 pr-4 outline-none focus:border-[#f4b400]" placeholder="Search products..."/></div></div>{filtered.length?<div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(p=><ProductCard key={p.id} product={p}/>)}</div>:<div className="rounded-3xl border border-dashed border-stone-300 p-16 text-center text-stone-500"><SlidersHorizontal className="mx-auto mb-3"/>{products.length?"No products match your filter.":"No products yet. Admins can add them from the dashboard."}</div>}</main></>
}
