import { Link } from "react-router-dom";
import { ArrowRight, Clock3, MapPin, ShoppingBag, Truck, Star, Coffee, HeartHandshake } from "lucide-react";
import { useEffect, useState } from "react";
import { listAll } from "../lib/firestore";
import ProductCard from "../components/ProductCard";

export function Home(){
 const [products,setProducts]=useState([]);
 useEffect(()=>{listAll("products").then(p=>setProducts(p.filter(x=>x.available!==false))).catch(()=>{})},[]);
 return <><section className="hero-grid relative overflow-hidden bg-[#2b2118] text-white"><div className="absolute inset-0 opacity-40" style={{backgroundImage:"linear-gradient(rgba(43,33,24,.72),rgba(43,33,24,.88)),url('/assets/Background.jpg')",backgroundSize:"cover",backgroundPosition:"center"}}/><div className="container-page relative grid min-h-[680px] items-center py-24 lg:grid-cols-2"><div className="max-w-2xl"><span className="mb-5 inline-flex rounded-full border border-[#f4b400]/40 bg-[#f4b400]/10 px-4 py-2 text-sm font-bold text-[#ffd76b]">KHMER COFFEE • PHNOM PENH</span><h1 className="text-5xl font-black leading-[1.05] tracking-tight sm:text-6xl lg:text-7xl">Brighten your day, <span className="text-[#f4b400]">one cup</span> at a time.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-stone-300">Bold coffee, quick service, and freshly prepared bites. Hop aboard the Khmer Tube and make every stop a good one.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/menu" className="inline-flex items-center gap-2 rounded-full bg-[#f4b400] px-6 py-3.5 font-black text-[#2b2118]">Order Now <ArrowRight size={18}/></Link><Link to="/about" className="rounded-full border border-white/20 px-6 py-3.5 font-bold hover:bg-white/10">Our Story</Link></div><div className="mt-10 flex flex-wrap gap-6 text-sm text-stone-300"><span className="flex items-center gap-2"><Clock3 size={17}/>Open daily</span><span className="flex items-center gap-2"><MapPin size={17}/>Phnom Penh</span><span className="flex items-center gap-2"><Star size={17}/>Made with pride</span></div></div></div></section>
 <section className="container-page py-20"><div className="mb-10 flex items-end justify-between gap-4"><div><p className="font-bold uppercase tracking-widest text-[#a76536]">Customer favorites</p><h2 className="mt-2 text-4xl font-black">Popular at TUBE</h2></div><Link to="/menu" className="hidden items-center gap-2 font-bold md:flex">View full menu <ArrowRight size={18}/></Link></div>{products.length?<div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{products.slice(0,4).map(p=><ProductCard key={p.id} product={p}/>)}</div>:<div className="rounded-3xl border border-dashed border-stone-300 p-10 text-center text-stone-500">Connect Firebase and add products to show the live menu.</div>}</section>
 <section className="bg-[#f1e9df] py-20"><div className="container-page grid gap-6 md:grid-cols-3"><Feature icon={Truck} title="Online ordering" text="Order ahead for takeaway or delivery."/><Feature icon={Coffee} title="Quality coffee" text="Reliable recipes and fresh ingredients."/><Feature icon={HeartHandshake} title="Khmer pride" text="A Cambodian brand made by Cambodians." /></div></section>
 </>;
}
function Feature({icon:Icon,title,text}){return <div className="rounded-3xl bg-white p-7 card-shadow"><span className="mb-5 grid h-12 w-12 place-items-center rounded-2xl bg-[#fff5cf] text-[#8b6700]"><Icon/></span><h3 className="text-xl font-black">{title}</h3><p className="mt-2 leading-7 text-stone-500">{text}</p></div>}
export function About(){return <Page title="Our story" kicker="ABOUT TUBE"><div className="grid gap-10 lg:grid-cols-2 lg:items-center"><div><p className="text-lg leading-8 text-stone-600">TUBE COFFEE was created by three Cambodian shareholders. Inspired by London's underground Tube, the brand stands for speed, reliable quality, and affordability.</p><p className="mt-5 text-lg leading-8 text-stone-600">As synonymous as the Tube is with London, TUBE Coffee aims to be the same in Cambodia — a Khmer brand created in Cambodia and made by Cambodians to compete with foreign brands. Yellow represents warmth, freshness, happiness, optimism, and positivity.</p><div className="mt-7 grid gap-4 sm:grid-cols-2"><Info title="Mission" text="Serve dependable, accessible coffee and food with a distinctly Khmer identity."/><Info title="Vision" text="Become an everyday coffee destination people can trust at every stop." /></div></div><div className="overflow-hidden rounded-[2rem] bg-[#f4b400] p-8"><img src="/assets/logo.png" className="mx-auto w-64 rounded-3xl bg-white p-8 shadow-2xl" alt="TUBE Coffee logo"/></div></div></Page>}
function Info({title,text}){return <div className="rounded-2xl border border-stone-200 bg-white p-5"><h3 className="font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-stone-500">{text}</p></div>}
export function Services(){const defaults=[["Dine-in","Settle in with your favorite coffee and a quick bite."],["Takeaway","Fast pickup when you are on the move."],["Online Ordering","Browse the menu and place your order anytime."],["Delivery","Get TUBE favorites delivered to your door."],["Special Coffee Services","Coffee solutions for meetings, teams, and special occasions."],["Fresh Food","Cambodian-inspired meals and snacks prepared for everyday fuel."]]; const [services,setServices]=useState([]); useEffect(()=>{listAll("services").then(rows=>setServices(rows.filter(x=>x.available!==false))).catch(()=>{})},[]); const visible=services.length?services:defaults.map(([title,description],i)=>({id:String(i),title,description})); return <Page title="Services made for your journey" kicker="WHAT WE DO"><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{visible.map((service,i)=><div key={service.id} className="rounded-3xl border border-stone-200 bg-white p-7 card-shadow"><span className="text-4xl font-black text-[#f4b400]">{String(i+1).padStart(2,"0")}</span><h3 className="mt-5 text-xl font-black">{service.title}</h3><p className="mt-2 leading-7 text-stone-500">{service.description}</p></div>)}</div></Page>}
export function Contact(){const [sent,setSent]=useState(false);return <Page title="Get in touch" kicker="CONTACT"><div className="grid gap-10 lg:grid-cols-2"><div className="rounded-3xl bg-[#2b2118] p-8 text-white"><h3 className="text-2xl font-black">Visit TUBE Coffee</h3><div className="mt-7 grid gap-5 text-stone-300"><p className="flex gap-3"><MapPin/>639 Kampuchea Krom Blvd (128), Phnom Penh</p><p className="flex gap-3"><Clock3/>Open daily • check your local branch for exact hours</p><p className="flex gap-3"><ShoppingBag/>Online ordering available</p></div></div><form onSubmit={e=>{e.preventDefault();setSent(true)}} className="rounded-3xl border border-stone-200 bg-white p-8 card-shadow">{sent?<div className="py-14 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-emerald-100 text-emerald-700">✓</div><h3 className="mt-4 text-2xl font-black">Message received</h3><p className="mt-2 text-stone-500">Thanks for reaching out to TUBE Coffee.</p></div>:<><h3 className="text-2xl font-black">Send a message</h3><div className="mt-6 grid gap-4"><input required className="rounded-xl border border-stone-200 px-4 py-3 outline-none focus:border-[#f4b400]" placeholder="Your name"/><input required type="email" className="rounded-xl border border-stone-200 px-4 py-3 outline-none focus:border-[#f4b400]" placeholder="Your email"/><textarea required rows="5" className="rounded-xl border border-stone-200 px-4 py-3 outline-none focus:border-[#f4b400]" placeholder="Your message"/><button className="rounded-xl bg-[#f4b400] px-5 py-3 font-black">Send message</button></div></>}</form></div></Page>}
function Page({title,kicker,children}){return <><div className="bg-[#2b2118] py-20 text-white"><div className="container-page"><p className="font-bold uppercase tracking-[.2em] text-[#f4b400]">{kicker}</p><h1 className="mt-3 text-5xl font-black">{title}</h1></div></div><main className="container-page py-16">{children}</main></>}
